
from area_sys import area_sys
from perf_sys import perf_sys
import numpy as np

#
# @author: Jonathan Ramírez.
#

# same output for both systems at same iterations.
block = np.array([0x61,0x69,0x63,0x70,0x21,0x00,0x00,0x03,0x17,0x08,0x00,0xf3])
target = 50

# no system works.
#block = np.array([0x73, 0xa9, 0xde, 0xbe, 0x6a, 0xf9, 0xc9, 0x5e, 0x9f, 0x05, 0x2d, 0x59])
#target = 9

# performance system used 43 iterations while area system used 524.
#block = np.array([0xeb, 0xad, 0x50, 0x90, 0x38, 0x43, 0xf9, 0xc9, 0xaa, 0xad, 0x6f, 0x64])
#target = 50

# area system used 30 iterations while performance system used 8 iterations.
#block = np.array([0x39, 0x7d, 0x9f, 0x2f, 0x40, 0xca, 0x9e, 0x6c, 0x6b, 0x1f, 0x33, 0x24])
#target = 50



start = 1

def main():
    valid_nonce_area = np.array([0, 0, 0, 0])
    finish_bus_area = 0


    valid_nonce_perf = np.array([0, 0, 0, 0])
    finish_bus_perf = 0

    
    print("------ Executing area improved system architecture:------", '\n')
    valid_nonce_area, finish_bus_area = area_sys(block, start, target)

    print("------ Nonce generated by the system:------", '\n')
    print("          ",valid_nonce_area, '\n')

    print("------ finish bus value generated by the system:------", '\n')
    print("          ",finish_bus_area, '\n')


    print("------ Executing performance improved system architecture:------", '\n')
    valid_nonce_perf, finish_bus_perf = perf_sys(block, start, target)

    print("------ Nonce generated by the system:------", '\n')
    print("          ",valid_nonce_perf, '\n')

    print("------ finish bus value generated by the system:------", '\n')
    print("          ",finish_bus_perf, '\n')


if __name__ == '__main__':
    main()